name: Frontend CI/CD

on:
  push:
    branches: ["staging"]
  pull_request:
    branches: ["staging"]

jobs:
  build-test-lint-analyze-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          echo "📦 Installing dependencies..."
          npm i

      - name: Run ESLint
        run: |
          echo "🔍 Running ESLint..."
          npm run lint || echo "::warning::Linting failed, check your code style!"
        continue-on-error: true

      # - name: Run Unit Tests
      #   run: |
      #     echo "🧪 Running Unit Tests..."
      #     npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            jrtr1/wandoor-frontend-app:frontend-${{ github.sha }}
            jrtr1/wandoor-frontend-app:frontend-latest

      # === Find & Replace image tag di repo infra branch (staging) ===
      - name: Checkout infra repository (staging)
        uses: actions/checkout@v3
        with:
          repository: kelompok-3-odp343/infra
          token: ${{ secrets.ACCESS_TOKEN }}
          path: infra
          ref: staging

      - name: Update image tag in frontend deployment
        run: |
          cd infra/k3s/frontend-wandoor
          sed -i "s|jrtr1/wandoor-frontend-app:.*|jrtr1/wandoor-frontend-app:frontend-${{ github.sha }}|g" frontend-deployment.yaml

      - name: Commit and push updated image tag
        run: |
          cd infra
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update frontend image tag to frontend-${{ github.sha }}"
          git push origin staging

      # === Find & Replace image tag di repo infra branch (main) ===
      - name: Checkout infra repository (main)
        uses: actions/checkout@v3
        with:
          repository: kelompok-3-odp343/infra
          token: ${{ secrets.ACCESS_TOKEN }}
          path: infra
          ref: main

      - name: Update image tag in frontend deployment
        run: |
          cd infra/v2/k3s-manifests/frontend-wandoor
          sed -i "s|jrtr1/wandoor-frontend-app:.*|jrtr1/wandoor-frontend-app:frontend-${{ github.sha }}|g" frontend-deployment.yaml

      - name: Commit and push updated image tag
        run: |
          cd infra
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update frontend image tag to frontend-${{ github.sha }}"
          git push origin main
